services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "music"
      POSTGRES_USER: "purple"
      POSTGRES_PASSWORD: "music_purple"
    ports:
      - "5432:5432"
    restart: always

  nextjs:
    image: ghcr.io/template-inc/prod-purple-nextjs:latest
    environment:
      DATABASE_URL: "postgresql://purple:music_purple@db:5432/music"
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - db
