services:
  db:
    environment:
      POSTGRES_DB: music
      POSTGRES_PASSWORD: music_purple
      POSTGRES_USER: purple
    image: postgres:13.3
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: always
  nextjs:
    command:
      - npm
      - run
      - start
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://purple:music_purple@db:5432/music
    image: ghcr.io/khodis/prod-purple-nextjs:latest
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
  prisma-studio:
    environment:
      DATABASE_URL: postgresql://purple:music_purple@db:5432/music
    image: prismagraphql/prisma:1.34
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 5555
        published: "5555"
        protocol: tcp
    depends_on:
      - db
networks:
  purple-net:
    name: purple-studio_purple-net
    driver: bridge
