services:
  db:
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: purple
      POSTGRES_PASSWORD: music_purple
    image: postgres:13.3
    ports:
      - "5432:5432" # Expose PostgreSQL port
    networks:
      - purple-net
    restart: always

  nextjs:
    image: ghcr.io/template-inc/prod-purple-nextjs:latest
    command: ["npm", "run", "start"]
    environment:
      DATABASE_URL: postgresql://purple:music_purple@db:5432/music
    depends_on:
      db:
        condition: service_healthy # Ensure db is ready before starting nextjs
    ports:
      - "3000:3000" # Expose Next.js on port 3000
    networks:
      - purple-net

  prisma-studio:
    image: prismagraphql/prisma:1.34 # Adjust to the correct version for Prisma Studio
    environment:
      DATABASE_URL: postgresql://purple:music_purple@db:5432/music
    ports:
      - "5555:5555" # Expose Prisma Studio on port 5555
    networks:
      - purple-net

networks:
  purple-net:
    driver: bridge
