services:
  db:
    environment:
      POSTGRES_DB: music
      POSTGRES_PASSWORD: music_purple
      POSTGRES_USER: purple
    image: postgres:latest
    networks:
      - purple-net
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs:
    depends_on:
      - db
    env_file:
      - .env
    image: ghcr.io/khodis/prod-purple-nextjs:latest
    networks:
      - purple-net
    ports:
      - "8040:80"

  nocodb:
    image: nocodb/nocodb:latest
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - purple-net
    ports:
      - "8030:8080"
    volumes:
      - "ncdata:/usr/app/data"

networks:
  purple-net:
    name: purple-studio_purple-net
    driver: bridge

volumes:
  pgdata:
  ncdata:

