services:
  db:
    environment:
      POSTGRES_DB: music
      POSTGRES_PASSWORD: music_purple
      POSTGRES_USER: purple
    image: postgres:latest
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs:
    command:
      - npm
      - run
      - start
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://purple:music_purple@db:5432/music
    image: ghcr.io/khodis/prod-purple-nextjs:latest
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp

  prisma-studio:
    environment:
      PRISMA_CONFIG: |
        port: 5555
        databases:
          default:
            connector: postgresql
            uri: 'postgresql://purple:music_purple@db:5432/music'
      DATABASE_URL: postgresql://purple:music_purple@db:5432/music
    image: prismagraphql/prisma:1.34
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 5555
        published: "5555"
        protocol: tcp
    depends_on:
      - db

  nocodb:
    image: nocodb/nocodb:latest
    depends_on:
      - db
    environment:
      NC_DB: "postgresql://purple:music_purple@db:5432/music"
    networks:
      purple-net: null
    ports:
      - mode: ingress
        target: 8080
        published: "4444"
        protocol: tcp
    volumes:
      - "ncdata:/usr/app/data"

networks:
  purple-net:
    name: purple-studio_purple-net
    driver: bridge

volumes:
  pgdata:
  ncdata:
