import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import React from "react";
import { Toaster } from "sonner";

import { auth } from "@/auth";
import { routing } from "@/i18n/routing";
import { NextAuthProvider } from "@/providers/NextAuthProvider";

import "./tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const session = await auth();

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <NextAuthProvider session={session}>{children}</NextAuthProvider>
        </NextIntlClientProvider>
        <Toaster closeButton />
      </body>
    </html>
  );
}

