import type { Metadata } from "next";
import React from "react";
import { Toaster } from "sonner";

import { initializeStudios } from "@/actions/mutation/initialize-studios";
import initTranslations from "@/app/i18n";
import { auth } from "@/auth";
import TranslationProvider from "@/components/providers/TranslationsProvider";
import { NextAuthProvider } from "@/providers/NextAuthProvider";

import "./tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const i18nNamespaces = ["index", "common", "auth", "my"];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const awaitedParams = await params;
  const locale = awaitedParams.locale;
  console.log("root: Loading RootLayout with locale:", locale);

  const session = await auth();

  await initializeStudios();

  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale}>
      <body>
        <TranslationProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          <NextAuthProvider session={session}>{children}</NextAuthProvider>
          <Toaster closeButton />
        </TranslationProvider>
      </body>
    </html>
  );
}
