name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Create env file"
        run: |
          touch .env
          echo "${{ secrets.DEPLOY_ENV }}" > .env

      - name: "Copy .env to server"
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: ".env"
          target: "/srv/deployments/prod-purple-nextjs/.env"

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "KhoDis"
          password: ${{ secrets.REGISTRY_KEY }}

      - name: "Build&Deploy purple-nextjs"
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags: |
            ghcr.io/khodis/prod-purple-nextjs:latest
          build-args: |
            build_mode=Release

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Copy docker-compose.prod-ci.yml to server"
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "docker-compose.prod-ci.yml"
          target: "/srv/deployments/prod-purple-nextjs/"

      - name: "Run deploy on server"
        uses: appleboy/ssh-action@master
        with:
          timeout: 60m
          command_timeout: 60m
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /srv/deployments/prod-purple-nextjs
            sudo docker compose -f docker-compose.prod-ci.yml -p prod down
            sudo docker compose -f docker-compose.prod-ci.yml -p prod pull
            sudo docker compose -f docker-compose.prod-ci.yml -p prod up -d
