name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "KhoDis"
          password: ${{ secrets.REGISTRY_KEY }}

      - name: "Build&Deploy purple-nextjs"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/khodis/prod-purple-nextjs:latest
          build-args: |
            build_mode=Release

      - name: "Run deploy on server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Deploying purple-nextjs..."
            echo "Current dir: $(pwd)"
            echo "Current ls: $(ls -la)"
            echo "Current docker: $(sudo docker ps -a)"
            echo "Current tree: $(tree .)"
            echo "Current tree -d: $(tree -d .)"
            echo "Writing the same stuff to the file..."
            mkdir "/info"
            echo "Current dir: $(pwd)" > "/info/current_dir.txt"
            echo "Current ls: $(ls -la)" > "/info/current_ls.txt"
            echo "Current docker: $(sudo docker ps -a)" > "/info/current_docker.txt"
            echo "Current tree: $(tree .)" > "/info/current_tree.txt"
            echo "Current tree -d: $(tree -d .)" > "/info/current_tree_d.txt"
            sudo docker-compose -f docker-compose.prod-ci.yml -p prod pull
            sudo docker-compose -f docker-compose.prod-ci.yml -p prod up -d
